const keywords = {
    verbs: [
        'taking home',
        'stewing',
        'vibrating',
        'ordering',
        'squeezing',
        'releasing',
        'fixing',
        'gamifying',
        'building',
        'revolutionizing',
        'reinventing',
        'brogramming',
        'leading',
        'leveraging',
        'crowd-sourcing',
        'growth-hacking',
        'evangalizing',
        'disrupting',
        'innovating',
        'pivotting',
        'crowdfunding',
        'unicornizing',
        'hustling',
        'bootstrapping',
        'angel investing',
        'scaling',
        'agile-ing',
        'synergizing',
        'monetizing',
        'AI-ifying',
        'buzzwording',
        'onboarding',
        'incubating',
        'accelerating',
        'gambling',
        'skunkworking',
        'fast-failing',
        'decentralizing',
        'accelerating',
        'slamming',
        'attacking',
        'raising',
        'drinking',
        'pontificating',
        'qa-ing',
        'designing',
        'troubleshooting',
        'wiring',
        'paradigm-shifting',
        'thought leading',
        'boosting',
        'questioning',
        'interrogating',
        'interviewing',
        'evaluating',
        'firing',
        'befriending',
        'behavioralizing',
        'moderating',
        'normalizing',
        'refining',
        'circling',
        'basting',
        'tasting',
        'marinating',
        'baking',
        'decorating',
        'broiling',
        'serving',
        'purchasing',
        'worrying',
        'selling',
        'hiring',
        'persuading',
        'bribing',
        'placating',
    ],
    prepositions: [
        'in',
        'on',
        'at',
        'through',
        'around',
        'into',
        'for',
        'between',
        'with',
        'from',
        'over',
        'to',
        'over',
        'under',
        'behind',
        'beneath',
        'above',
        'below',
        'beside',
        'by',
        'down',
        'across',
        'along',
        'upon',
        'beyond',
        'toward',
        'towards',
        'in front of',
        'in light of',
        'on top of',
    ],
    adjectives: [
        'juiced',
        'hot',
        'broken',
        'good',
        'destitute',
        'r.i.p.',
        'bleeding-edge',
        'disruptive',
        'fresh',
        'dead',
        'spicy',
        'next-gen',
        'last-gen',
        'freemium',
        'game-changing',
        'pivotable',
        'scaleable',
        'disruptopreneurial',
        'hypergrowth',
        'stealth',
        'pivotal',
        'cash-bleeding',
        'buzzworthy',
        'scalable',
        'pre-revenue',
        'agile',
        'cash-burning',
        'stealth-mode',
        'synergistic',
        'bootstrapped',
        'paradigm-shifted',
        'blockchain-enabled',
        'AI-enabled',
        'web3',
        'ML-enabled',
        'ChatGPT-Enhanced',
        'AI-influenced',
        'AI-Driven',
        'AI-Engineered',
        'competitive',
        'crowd-sourced',
        'crowd-prepared',
        'driven',
        'dramatic',
        'fairy-tale-like',
        'glamorous',
        'gorgeous',
        'high-growth',
        'magical',
        'mystical',
        'new',
        'original',
        'supersonic',
        'large',
        'in-charge',
        'tiny',
        'massive',
        'vibrant',
        'dynamic',
        'arrogant',
        'error-prone',
        'unusual',
        'unstable',
        'deranged',
        'independent',
        'unpredictable',
        'weak-willed',
        'inferior',
        'poorly-secured',
        'poorly-coded',
        'poor',
        'unproductive',
        'unfortunate',
        'poorly-recieved',
        'well-recieved',
        'awkward',
        'bloated',
        'agressive',
        'unfair',
        'canadian',
        'american',
        'toronto-based',
        'nebraska-based',
        'montreal-based',
        'texas-based',
        'nebraskan',
        'texan',
        'american',
        'torontonian',
        'half-baked'
    ],
    nouns: [
        { word: 'code', plural: true },
        { word: 'copy', plural: true },
        { word: 'democracy', plural: false },
        { word: 'computer', plural: false },
        { word: 'drugs', plural: true },
        { word: 'synergy', plural: false },
        { word: 'experience', plural: false },
        { word: 'passion', plural: true },
        { word: 'MVP', plural: false },
        { word: 'vaporware', plural: true } ,
        { word: 'ROI', plural: true },
        { word: 'platform', plural: false },
        { word: 'blockchain', plural: false },
        { word: 'Chase™ Sapphire Card', plural: false },
        { word: "Free Shopping Bags", plural: true },
        { word: "Nebraska Corn", plural: true },
        { word: "🛫", plural: false },
        { word: "Papa Johns™ cheese sauce", plural: true },
        { word: "podcast", plural: false },
        { word: "caffeine", plural: false },
        { word: "Credit Card Points", plural: true },
        { word: "vibration", plural: true },
        { word: "semicolon", plural: false },
        { word: 'exhaustion', plural: false },
        { word: 'wankel', plural: false },
        { word: 'GFuel™', plural: true },
        { word: 'the Torch', plural: false },
        { word: 'disruption', plural: false },
        { word: 'innovation', plural: false },
        { word: 'startup', plural: true },
        { word: 'exit strategy', plural: false },
        { word: 'valuation', plural: true },
        { word: 'unicorns', plural: true },
        { word: 'hustle', plural: true },
        { word: 'venture capital', plural: false },
        { word: 'pitch deck', plural: false },
        { word: 'angel investor', plural: false },
        { word: 'accelerator', plural: false },
        { word: 'incubator', plural: false },
        { word: 'agile methodology', plural: true },
        { word: 'burn rate', plural: true },
        { word: 'cash flow', plural: true },
        { word: 'disruptive technology', plural: true },
        { word: 'growth hacks', plural: true },
        { word: 'early adopter', plural: true },
        { word: 'beta testing', plural: true },
        { word: 'disruptopreneur', plural: false },
        { word: 'angel round', plural: false },
        { word: 'unicorn hunter', plural: false },
        { word: 'scale-up', plural: false },
        { word: 'pivot', plural: false },
        { word: 'exit strategy', plural: false },
        { word: 'acqui-hire', plural: false },
        { word: 'stealth startup', plural: false },
        { word: 'synergy', plural: false },
        { word: 'charts', plural: true },
        { word: 'chart', plural: false },
        { word: 'data', plural: true },
        { word: 'metrics', plural: true },
        { word: 'analytics', plural: true },
        { word: 'table', plural: false },
        { word: 'database', plural: false },
        { word: 'value', plural: false },
        { word: 'value', plural: true },
        { word: 'values', plural: true },
        { word: 'maps', plural: true },
        { word: 'map', plural: false },
        { word: 'bubble', plural: false },
        { word: 'story', plural: false },
        // product
        { word: 'product', plural: false },
        // library
        { word: 'library', plural: false },
        // package
        { word: 'package', plural: false },
        //industry
        { word: 'industry', plural: false },
        { word: 'intranet', plural: false },
        { word: 'internet', plural: false },
        { word: 'fortune 500', plural: false },
        { word: 'IPO', plural: false },
        { word: 'series-a', plural: false },
        { word: 'seed round', plural: false },
        { word: 'aquisition', plural: false },
        { word: 'computer', plural: false },
        { word: '😬', plural: false },
        { word: 'customer', plural: false },
        { word: 'ai model', plural: false },
        { word: 'virus', plural: false },
        { word: 'back door', plural: false },
        { word: 'rootkit', plural: false },
        { word: 'meme', plural: false },
        { word: 'memes', plural: true },
        { word: 'beer', plural: false },
        { word: 'alcohol', plural: false },
        { word: 'liquor', plural: false },
        { word: 'process', plural: false },
        { word: 'company', plural: false },
        { word: 'cash', plural: false },
        { word: 'offshore bank account', plural: false },
        { word: 'offshore bank accounts', plural: true },
        { word: 'toronto', plural: false },
        { word: 'canada', plural: false },
        { word: 'montreal', plural: false },
        { word: 'nebraska', plural: false },
        { word: 'texas', plural: false },
        { word: 'america', plural: false },
        { word: 'maple syrup', plural: false },
        { word: 'disaster', plural: false },
        { word: 'buy-in', plural: false },
        { word: 'road map', plural: false },
        { word: 'road maps', plural: true },
    ]
};

const adjective_chance = 0.8
const double_adjective_chance = 0.1
const preposition_chance = 0.5

export default function (): string {
    const adj = Math.random() < adjective_chance 
        ? keywords.adjectives[Math.floor(keywords.adjectives.length * Math.random())] + " "
        : '' ;
    
    const adj2 = adj ? Math.random() < double_adjective_chance 
        ? keywords.adjectives[Math.floor(keywords.adjectives.length * Math.random())] + " "
        : '' : '' ;

    const preposition = Math.random() < preposition_chance
        ? keywords.prepositions[Math.floor(keywords.prepositions.length * Math.random())] + " "
        : '' ;

    const verb = keywords.verbs[Math.floor(keywords.verbs.length * Math.random())] + " ";
    const noun = keywords.nouns[Math.floor(keywords.nouns.length * Math.random())];

    const nounPluralityMod = (noun.plural)
        ? ' '
            : ['a','e','i','o','u'].includes(adj2[0] || adj[0] || noun.word[0]) 
            ? ' an ' : ' a '
            

    return `${verb}${preposition}${nounPluralityMod}${adj2}${adj}${noun.word}`;
}
